config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'dashboard#index'

  get 'dashboard/index'

  resources :notes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/note.rb
class Note < ApplicationRecord
  has_rich_text :content

  # Validations
  validates :name, :icon, :color, presence: true

  belongs_to :user

  scope :by_user, ->(user) { where(user_id: user) }
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :email, presence: true, uniqueness: true

  has_many :notes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :require_login
  helper_method :current_user
  include SessionsHelper
  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    else
      @current_user = nil
    end
  end

  def require_login
    return if logged_in?

    flash[:error] = 'require_login'
    redirect_to new_session_path
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @notes = Note.by_user(current_user)
    @host = request.host
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if current_user.present?
      redirect_to dashboard_index_path
    else
      redirect_to root_url
    end
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [:show, :edit, :update, :destroy]

  def new
    @note = Note.new
  end

  def create
    @note = Note.new(note_params)
    @note.user = current_user
    if @note.save
      flash[:success] = 'Criado com sucesso!'
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @note.update(note_params)
      flash[:success] = 'Atualizado com sucesso!'
      redirect_back(fallback_location: root_path)
    else
      render :edit
    end
  end

  def destroy
    if @note.destroy
      redirect_to root_path, notice: :destroyed
    else
      redirect_to root_path, alert: @note.errors[:base]&.first
    end
  end

  private

  def set_note
    @note = Note.find(params[:id])
  end

  def note_params
    params.require(:note).permit(:name, :color, :icon, :description, :content)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login

  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: "Logged in!"
    else
      flash.now[:alert] = "Email or password is invalid"
      render "new"
    end
  end
  def destroy
    session[:user_id] = nil
    redirect_to new_session_path, notice: "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user=(user)
    @current_user = user
  end

  def current_user
    # To run the find only 1 time use memoization ||=
    @current_user ||= User.find_by(auth_token: session[:auth_token])
  end

  def logged_in?
    current_user.present?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/dashboard/index.html.erb
<div class="row mt-5">
  <div class="btn-group ml-3 col-md-2">
    <%= link_to new_note_path, class: 'btn btn-info' do %>
      Adicionar
      <i class="m-l-5 fa fa-plus"></i>
    <% end %>
  </div>
  <div class="btn-group ml-3 col-md-8">
    <div class="col-md-offset-5 mx-auto">
      <h3>Notas</h3>
    </div>
  </div>
</div>

<div class="row mt-5">
  <h1><%= @host %></h1>
  <% @notes.find_each do |note| %>
    <div class="card ml-3 mt-3" style="width: 16rem; background-color: <%= note.color %>">
      <div class="card-body">
        <div class="d-flex justify-content-center">
          <i class="<%= note.icon %> fa-3x"></i>
        </div>
        <div class="d-flex justify-content-center">
          <h5 class="card-title"><%= note.name %></h5>
        </div>
        <%= link_to edit_note_path(note), class: 'btn btn-info btn-sm' do %>
          Ver Notas
          <i class="fas fa-edit"></i>
        <% end %>
        <%= link_to note, method: :delete, data: { confirm: 'Tem a certeza' }, class: 'btn btn-info btn-sm' do %>
          <i class="far fa-trash-alt"></i>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <%= link_to 'Notas', root_path, class: 'navbar-brand' %>
    <div class="d-flex flex-row-reverse">
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
          <% if current_user %>
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="#">Olá <%= current_user.email %>.</a>
            </li>
            <li class="nav-item">
              <%= link_to "Log Out", logout_path, class: 'nav-link active' %></a>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "Log In", login_path, class: 'nav-link active' %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Notes</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!-- START Navbar -->
    <%= render 'layouts/navbar' %>

    <div class="content">
      <div class="container">
        <%= yield %>
      </div>
    </div>

  </body>
</html>

app/views/notes/edit.html.erb
<div class="row px-5">
  <div class="col-lg-12">
    <div class="panel-body px-5">
      <div class="container pt-4">
        <div id="notice" class="noticesWrapper">
          <% flash.each do |name, msg| %>
            <div class="alert alert-success alert-dismissible fade show" role="alert">
              <%= t msg, default: msg %>
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>              
          <% end %>
        </div>
        </script>
        <%= form_with(model: @note, local: true) do |f| %>
          <% if @note.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@note.errors.count, "error") %> prohibited this   note from being saved:</h2>
              <ul>
                <% @note.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>
          <div class="row">
            <div class="form-group col-md-5">
              <%= f.label :name do %>
                Nome</span>
              <% end %>
              <%= f.text_field :name, class: 'form-control' %>
              <% if @note.errors[:name].present? %>
                <span class="help-block text-danger">
                  <small><%= @note.errors[:name].first %></small>
                </span>
              <% end %>
            </div>
            <div class="form-group col-md-4">
              <%= f.label :icon do %>
                Icon</span>
              <% end %>
              <div class="col-sm-12">
                <%= f.text_field :icon, class: 'form-control', placeholder: 'icon' %>
              </div>
            </div>
            <div class="form-group col-md-3">
              <%= f.label :color do %>
                Cor</span>
              <% end %>
              <div class="col-sm-12">
                <%= f.color_field :color, class: 'form-control', placeholder: 'color' %>
              </div>
            </div>
          </div>
          <div class="field">
            <%= f.label :content do %>
              Conteúdo</span>
            <% end %>
            <%= f.rich_text_area :content %>
          </div>
          <div class="row mt-3">
            <div class="col-sm-offset-2 col-sm-10 m-t-15">
              <%= f.submit 'Guardar', class: 'btn btn-primary' %>
              <%= link_to 'Cancelar', root_path, class: "btn btn-secondary m-l-5" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

  

app/views/notes/new.html.erb
<div class="row px-5">
  <div class="col-lg-12">
    <div class="panel-body px-5">
      <div class="container pt-4">
        <%= form_with model: @note, role: 'form', class: 'form-horizontal' do |f| %>
          <h3 style="text-align:center">Adicionar uma nova categoria</h3>
          <div class="row mt-5">
            <div class="form-group col-md-8">
              <%= f.label :name do %>
                Nome</span>
              <% end %>
              <%= f.text_field :name, class: 'form-control' %>
              <% if @note.errors[:name].present? %>
                <span class="help-block text-danger">
                  <small><%= @note.errors[:name].first %></small>
                </span>
              <% end %>
            </div>
            <div class="form-group col-md-4">
              <%= f.label :color do %>
                Cor</span>
              <% end %>
              <div class="col-sm-12">
                <%= f.color_field :color, class: 'form-control', placeholder: 'color' %>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="form-group col-md-8">
              <%= f.label :icon do %>
                Icon Font Awesome</span>
              <% end %>
              <%= f.text_field :icon, class: 'form-control' %>
              <% if @note.errors[:icon].present? %>
                <span class="help-block text-danger">
                  <small><%= @note.errors[:icon].first %></small>
                </span>
              <% end %>
            </div>
          </div>
          <div class="row mt-3">
            <div class="col-sm-offset-2 col-sm-10 m-t-15">
              <%= f.submit 'Guardar', class: 'btn btn-primary' %>
              <%= link_to 'Cancelar', root_path, class: "btn btn-secondary m-l-5" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

  

app/views/notes/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Title:</strong>
  <%= @note.name %>
</p>
<p>
  <strong>Content:</strong>
  <%= @note.content %>
</p>
<%= link_to 'Edit', edit_note_path(@note) %> |
<%= link_to 'Back', notes_path %>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>